### ISSUE TITLE
生成不了exe

### ISSUE THREAD

**Issue by AgentWRY** [shen-h/file-and-folder-locker#2]
两个密码都设了 7zip也装了 但是双击还只是隐藏 依然是批处理

**Comment by shen-h** [comment]
可能7z没装在PATH里？在CMD输入`7z`然后回车，应该有usage。如果是command not found之类的，解决方法就是把`7z.exe`加到PATH里。如果正常但还是生成不了exe，试下能否在CMD直接运行`7z a -p"<exe_password>" -sdel -mhe=on -sfx "<exe_filename_w_extension>" "<script_filename_w_extension>"` （替换掉尖括号部分）。相关代码在[commit 9a7b326 line 276](https://github.com/shen-h/file-and-folder-locker/blob/9a7b32623f1adac2c372e011f9a2e3465f7d47fa/windows_batch_script/.toggle_secret_files.bat#L276)。

**Comment by AgentWRY** [comment]
> 可能7z没装在PATH里？在CMD输入`7z`然后回车，应该有usage。如果是command not found之类的，解决方法就是把`7z.exe`加到PATH里。如果正常但还是生成不了exe，试下能否在CMD直接运行`7z a -p"<exe_password>" -sdel -mhe=on -sfx "<exe_filename_w_extension>" "<script_filename_w_extension>"` （替换掉尖括号部分）。相关代码在[commit 9a7b326 line 276](https://github.com/shen-h/file-and-folder-locker/blob/9a7b32623f1adac2c372e011f9a2e3465f7d47fa/windows_batch_script/.toggle_secret_files.bat#L276)。

加到path里解锁了 感谢 hhhh 很好用

**Comment by AgentWRY** [comment]
> > 可能7z没装在PATH里？在CMD输入`7z`然后回车，应该有usage。如果是command not found之类的，解决方法就是把`7z.exe`加到PATH里。如果正常但还是生成不了exe，试下能否在CMD直接运行`7z a -p"<exe_password>" -sdel -mhe=on -sfx "<exe_filename_w_extension>" "<script_filename_w_extension>"` （替换掉尖括号部分）。相关代码在[commit 9a7b326 line 276](https://github.com/shen-h/file-and-folder-locker/blob/9a7b32623f1adac2c372e011f9a2e3465f7d47fa/windows_batch_script/.toggle_secret_files.bat#L276)。
> 
> 加到path里解锁了 感谢 hhhh 很好用

解决了

**Comment by shen-h** [comment]
> > 可能7z没装在PATH里？在CMD输入`7z`然后回车，应该有usage。如果是command not found之类的，解决方法就是把`7z.exe`加到PATH里。如果正常但还是生成不了exe，试下能否在CMD直接运行`7z a -p"<exe_password>" -sdel -mhe=on -sfx "<exe_filename_w_extension>" "<script_filename_w_extension>"` （替换掉尖括号部分）。相关代码在[commit 9a7b326 line 276](https://github.com/shen-h/file-and-folder-locker/blob/9a7b32623f1adac2c372e011f9a2e3465f7d47fa/windows_batch_script/.toggle_secret_files.bat#L276)。
> 
> 加到path里解锁了 感谢 hhhh 很好用

不客气，使用愉快(/ω＼)

**Comment by txxxtxx** [comment]
我还是不行啊
